#kere# #k'erre# 0 0 { type = 16 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'erre# #kere# 0 0 { type = 16 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pere# #p'erre# 0 0 { type = 16 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'erre# #pere# 0 0 { type = 16 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pogri# #p'okri# 0 0 { type = 16 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'okri# #pogri# 0 0 { type = 16 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tare# #t'arre# 0 0 { type = 16 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'arre# #tare# 0 0 { type = 16 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#agu# #'akku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'akku# #agu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#hagu# #h'akku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#h'akku# #hagu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#hägu# #h'äkku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#h'äkku# #hägu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#idu# #'ittu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'ittu# #idu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#iga# #'ikka# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'ikka# #iga# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#jagu# #j'akku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#j'akku# #jagu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#juga# #j'ukka# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#j'ukka# #juga# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kabu# #k'appu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'appu# #kabu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kadu# #k'attu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'attu# #kadu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#koda# #k'otta# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'otta# #koda# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kubu# #k'uppu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'uppu# #kubu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kude# #k'utte# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'utte# #kude# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kägu# #k'äkku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'äkku# #kägu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#ladu# #l'attu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'attu# #ladu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#lagu# #l'akku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'akku# #lagu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#ligu# #l'ikku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'ikku# #ligu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#luba# #l'uppa# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'uppa# #luba# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#luga# #l'ukka# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'ukka# #luga# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#lugu# #l'ukku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'ukku# #lugu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#madu# #m'attu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#m'attu# #madu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#magu# #m'akku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#m'akku# #magu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#nadu# #n'attu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#n'attu# #nadu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#nuga# #n'ukka# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#n'ukka# #nuga# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#nõbu# #n'õppu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#n'õppu# #nõbu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#nõgu# #n'õkku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#n'õkku# #nõgu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#nägu# #n'äkku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#n'äkku# #nägu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pada# #p'atta# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'atta# #pada# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pagu# #p'akku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'akku# #pagu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pidu# #p'ittu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'ittu# #pidu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pragu# #pr'akku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#pr'akku# #pragu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pügi# #p'ükki# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'ükki# #pügi# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#rada# #r'atta# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#r'atta# #rada# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#rida# #r'itta# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#r'itta# #rida# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#ruga# #r'ukka# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#r'ukka# #ruga# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#sada# #s'atta# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'atta# #sada# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#sadu# #s'attu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'attu# #sadu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#sagu# #s'akku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'akku# #sagu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#siga# #s'ikka# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'ikka# #siga# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#suga# #s'ukka# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'ukka# #suga# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#sugu# #s'ukku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'ukku# #sugu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#sõda# #s'õtta# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'õtta# #sõda# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tegu# #t'ekku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'ekku# #tegu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tigu# #t'ikku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'ikku# #tigu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tuba# #t'uppa# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'uppa# #tuba# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tõde# #t'õtte# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'õtte# #tõde# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#uba# #'uppa# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'uppa# #uba# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#vagu# #v'akku# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#v'akku# #vagu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#vedu# #v'ettu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#v'ettu# #vedu# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#viga# #v'ikka# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#v'ikka# #viga# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#õde# #'õtte# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'õtte# #õde# 0 0 { type = 18 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#hane# #h'anne# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#h'anne# #hane# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kuse# #k'usse# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'usse# #kuse# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#love# #l'ovve# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'ovve# #love# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#lume# #l'umme# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'umme# #lume# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#lõhe# #l'õhhe# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'õhhe# #lõhe# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#lõve# #l'õvve# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'õvve# #lõve# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#läve# #l'ävve# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'ävve# #läve# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#mere# #m'erre# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#m'erre# #mere# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#mõne# #0# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#0# #m'õnne# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#nime# #n'imme# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#n'imme# #nime# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#suve# #s'uvve# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'uvve# #suve# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#süle# #s'ülle# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'ülle# #süle# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tule# #t'ulle# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'ulle# #tule# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tüve# #t'üvve# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'üvve# #tüve# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#une# #'unne# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'unne# #une# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#vere# #v'erre# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#v'erre# #vere# 0 0 { type = 20 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#jõge# #j'õkke# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#j'õkke# #jõge# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#lage# #l'akke# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'akke# #lage# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#mäge# #m'äkke# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#m'äkke# #mäge# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#nõge# #n'õkke# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#n'õkke# #nõge# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#rege# #r'ekke# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#r'ekke# #rege# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tuge# #t'ukke# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'ukke# #tuge# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tõbe# #t'õppe# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'õppe# #tõbe# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#väge# #v'äkke# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#v'äkke# #väge# 0 0 { type = 21 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#raba# #r'appa# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#r'appa# #raba# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#saba# #s'appa# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'appa# #saba# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pada# #p'atta# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'atta# #pada# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#ida# #'itta# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'itta# #ida# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#muda# #m'utta# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#m'utta# #muda# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#häda# #h'ätta# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#h'ätta# #häda# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#keha# #k'ehha# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'ehha# #keha# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#maja# #m'ajja# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#m'ajja# #maja# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#oja# #'ojja# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'ojja# #oja# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kõla# #k'õlla# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'õlla# #kõla# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#küla# #k'ülla# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'ülla# #küla# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#nina# #n'inna# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#n'inna# #nina# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kera# #k'erra# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'erra# #kera# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pesa# #p'essa# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'essa# #pesa# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#osa# #'ossa# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'ossa# #osa# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#võsa# #v'õssa# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#v'õssa# #võsa# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kava# #k'avva# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'avva# #kava# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#abi# #'appi# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'appi# #abi# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#klubi# #kl'uppi# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#kl'uppi# #klubi# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tüli# #t'ülli# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'ülli# #tüli# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pori# #p'orri# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'orri# #pori# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kõri# #k'õrri# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'õrri# #kõri# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kivi# #k'ivvi# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'ivvi# #kivi# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#rivi# #r'ivvi# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#r'ivvi# #rivi# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kino# #k'inno# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'inno# #kino# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kubu# #k'uppu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#k'uppu# #kubu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pidu# #p'ittu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'ittu# #pidu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#udu# #'uttu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'uttu# #udu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#ihu# #'ihhu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'ihhu# #ihu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#aju# #'ajju# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'ajju# #aju# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#tuju# #t'ujju# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'ujju# #tuju# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#salu# #s'allu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#s'allu# #salu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#talu# #t'allu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'allu# #talu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#elu# #'ellu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'ellu# #elu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#oleskelu# #olesk'ellu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#olesk'ellu# #oleskelu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#mõtiskelu# #mõtisk'ellu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#mõtisk'ellu# #mõtiskelu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#l'oetelu# #l'oet'ellu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#l'oet'ellu# #l'oetelu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#keskustelu# #keskust'ellu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#keskust'ellu# #keskustelu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#arutelu# #arut'ellu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#arut'ellu# #arutelu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#usutelu# #usut'ellu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#usut'ellu# #usutelu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#mälu# #m'ällu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#m'ällu# #mälu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#haru# #h'arru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#h'arru# #haru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#maru# #m'arru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#m'arru# #maru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#taru# #t'arru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'arru# #taru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#eru# #'erru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#'erru# #eru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#toru# #t'orru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#t'orru# #toru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#võru# #v'õrru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#v'õrru# #võru# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#pesu# #p'essu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#p'essu# #pesu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
#kräsu# #kr'ässu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = 0g: stem_transform = postrule }
#kr'ässu# #kräsu# 0 0 { type = 17 && stem_transform = preexc && stem_grammar = g0: stem_transform = postrule }
