#0# #'ahke# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #'akne# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #faksiimile# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #h'aige# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #h'elde# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #h'elge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #'ilge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #j'ulge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'aame# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'albe# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'alge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'ange# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #karate# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'arge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'arske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'auge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'erge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #kevade# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #kiherme# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'irbe# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'õrge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #l'ahke# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #l'auge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #l'eebe# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #l'eige# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #l'embe# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #l'ämbe# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #l'ääge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #m'albe# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #medrese# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #m'ähke# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #m'ätske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #n'iiske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #n'ilbe# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #n'õtke# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #n'ätske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #p'ehme# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #pr'iske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'ahke# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'ambe# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'ange# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'aske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'auge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'eede# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'ohke# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'uske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'uuge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'õske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'õuge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #r'äige# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #s'elge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #s'irge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #s'itke# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #s'olge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #suviste# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #s'ünge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #t'ahke# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #t'ihke# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #t'urske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #t'üüne# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #udehe# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #'uhke# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #v'aane# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #v'alge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #v'inge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #v'intske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #v'irge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #v'änge# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #v'ärske# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #'õige# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #'ülbe# 0 0 { type = 01 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #kevade# 0 0 { type = 02 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'õrbe# 0 0 { type = 02 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #k'öömne# 0 0 { type = 02 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#0# #tuhande# 0 0 { type = 02 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#m'andri# #m'andre# 0 0 { type = 03 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#m'andre# #m'andri# 0 0 { type = 03 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#t'andri# #t'andre# 0 0 { type = 03 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#t'andre# #t'andri# 0 0 { type = 03 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#k'alli# #k'alle# 0 0 { type = 05 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#k'alle# #k'alli# 0 0 { type = 05 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#k'auni# #k'aune# 0 0 { type = 05 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#k'aune# #k'auni# 0 0 { type = 05 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#'alti# #'alte# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#'alte# #'alti# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#k'alli# #k'alle# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#k'alle# #k'alli# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#k'auni# #k'aune# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#k'aune# #k'auni# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#m'alni# #m'alne# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#m'alne# #m'alni# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#n'aeri# #n'aere# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#n'aere# #n'aeri# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#n'ukri# #n'ukre# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#n'ukre# #n'ukri# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#r'ukki# #r'ukke# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#r'ukke# #r'ukki# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#s'ulni# #s'ulne# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#s'ulne# #s'ulni# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#t'uhli# #t'uhle# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#t'uhle# #t'uhli# 0 0 { type = 07 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#ab'ee# #ab'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#ab'e# #ab'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#all'ee# #all'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#all'e# #all'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#apog'ee# #apog'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#apog'e# #apog'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#arg'oo# #arg'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#arg'o# #arg'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#arm'ee# #arm'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#arm'e# #arm'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#assambl'ee# #assambl'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#assambl'e# #assambl'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#ataš'ee# #ataš'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#ataš'e# #ataš'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#atelj'ee# #atelj'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#atelj'e# #atelj'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#atsk'oo# #atsk'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#atsk'o# #atsk'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#bes'ee# #bes'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#bes'e# #bes'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#bid'ee# #bid'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#bid'e# #bid'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#bistr'oo# #bistr'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#bistr'o# #bistr'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#bord'oo# #bord'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#bord'o# #bord'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#brül'ee# #brül'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#brül'e# #brül'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#bukl'ee# #bukl'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#bukl'e# #bukl'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#bür'oo# #bür'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#bür'o# #bür'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#daf'ee# #daf'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#daf'e# #daf'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#defil'ee# #defil'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#defil'e# #defil'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#dekolt'ee# #dekolt'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#dekolt'e# #dekolt'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#dep'oo# #dep'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#dep'o# #dep'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#din'ee# #din'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#din'e# #din'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#draž'ee# #draž'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#draž'e# #draž'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#dubl'ee# #dubl'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#dubl'e# #dubl'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#ep'ee# #ep'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#ep'e# #ep'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#ess'ee# #ess'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#ess'e# #ess'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#fabli'oo# #fabli'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#fabli'o# #fabli'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#fil'ee# #fil'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#fil'e# #fil'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#frot'ee# #frot'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#frot'e# #frot'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#fuaj'ee# #fuaj'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#fuaj'e# #fuaj'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#glass'ee# #glass'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#glass'e# #glass'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#hartš'oo# #hartš'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#hartš'o# #hartš'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#id'ee# #id'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#id'e# #id'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kabar'ee# #kabar'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kabar'e# #kabar'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kalif'ee# #kalif'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kalif'e# #kalif'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kam'ee# #kam'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kam'e# #kam'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kanap'ee# #kanap'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kanap'e# #kanap'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#karr'ee# #karr'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#karr'e# #karr'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kašn'ee# #kašn'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kašn'e# #kašn'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kašp'oo# #kašp'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kašp'o# #kašp'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kliš'ee# #kliš'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kliš'e# #kliš'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kolj'ee# #kolj'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kolj'e# #kolj'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kombin'ee# #kombin'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kombin'e# #kombin'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#komit'ee# #komit'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#komit'e# #komit'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kommünik'ee# #kommünik'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kommünik'e# #kommünik'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#konferansj'ee# #konferansj'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#konferansj'e# #konferansj'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#korüf'ee# #korüf'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#korüf'e# #korüf'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#krupj'ee# #krupj'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#krupj'e# #krupj'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kup'ee# #kup'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kup'e# #kup'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kupl'ee# #kupl'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kupl'e# #kupl'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#k'uu# #k'u# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#k'u# #k'uu# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#kür'ee# #kür'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#kür'e# #kür'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#lam'ee# #lam'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#lam'e# #lam'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#land'oo# #land'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#land'o# #land'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#livr'ee# #livr'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#livr'e# #livr'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#l'uu# #l'u# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#l'u# #l'uu# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#m'aa# #m'a# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#m'a# #m'aa# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#mant'oo# #mant'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#mant'o# #mant'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#metr'oo# #metr'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#metr'o# #metr'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#monpansj'ee# #monpansj'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#monpansj'e# #monpansj'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#moralit'ee# #moralit'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#moralit'e# #moralit'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#moš'ee# #moš'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#moš'e# #moš'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#muar'ee# #muar'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#muar'e# #muar'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#mulin'ee# #mulin'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#mulin'e# #mulin'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#m'uu# #0# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#m'uu# #m'u# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#m'u# #m'uu# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#negliž'ee# #negliž'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#negliž'e# #negliž'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#niv'oo# #niv'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#niv'o# #niv'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#orhid'ee# #orhid'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#orhid'e# #orhid'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#pal'ee# #pal'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#pal'e# #pal'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#pann'oo# #pann'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#pann'o# #pann'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#papj'eemaš'ee# #papj'eemaš'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#papj'eemaš'e# #papj'eemaš'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#pensn'ee# #pensn'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#pensn'e# #pensn'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#perig'ee# #perig'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#perig'e# #perig'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#pik'ee# #pik'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#pik'e# #pik'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#plat'oo# #plat'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#plat'o# #plat'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#pliss'ee# #pliss'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#pliss'e# #pliss'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#portj'ee# #portj'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#portj'e# #portj'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#p'ortmon'ee# #p'ortmon'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#p'ortmon'e# #p'ortmon'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#portr'ee# #portr'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#portr'e# #portr'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#portup'ee# #portup'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#portup'e# #portup'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#pralin'ee# #pralin'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#pralin'e# #pralin'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#protež'ee# #protež'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#protež'e# #protež'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#p'uu# #p'u# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#p'u# #p'uu# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#pügm'ee# #pügm'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#pügm'e# #pügm'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#pür'ee# #pür'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#pür'e# #pür'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#rantj'ee# #rantj'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#rantj'e# #rantj'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#rel'ee# #rel'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#rel'e# #rel'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#renom'ee# #renom'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#renom'e# #renom'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#resüm'ee# #resüm'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#resüm'e# #resüm'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#rokok'oo# #rokok'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#rokok'o# #rokok'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#rond'oo# #rond'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#rond'o# #rond'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#rul'oo# #rul'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#rul'o# #rul'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#s'oo# #s'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#s'o# #s'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#suar'ee# #suar'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#suar'e# #suar'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#sufl'ee# #sufl'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#sufl'e# #sufl'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#sup'ee# #sup'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#sup'e# #sup'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#s'uu# #0# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#s'uu# #s'u# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#s'u# #s'uu# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#süž'ee# #süž'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#süž'e# #süž'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#ševr'oo# #ševr'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#ševr'o# #ševr'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#žab'oo# #žab'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#žab'o# #žab'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#žel'ee# #žel'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#žel'e# #žel'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#tabl'oo# #tabl'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#tabl'o# #tabl'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#t'ee# #0# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#t'ee# #t'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#t'e# #t'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#tir'ee# #tir'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#tir'e# #tir'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#trahh'ee# #trahh'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#trahh'e# #trahh'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#tranš'ee# #tranš'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#tranš'e# #tranš'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#trik'oo# #trik'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#trik'o# #trik'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#trof'ee# #trof'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#trof'e# #trof'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#tr'uu# #tr'u# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#tr'u# #tr'uu# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#trüm'oo# #trüm'o# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#trüm'o# #trüm'oo# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#turn'ee# #turn'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#turn'e# #turn'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#turnik'ee# #turnik'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#turnik'e# #turnik'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#t'öö# #t'ö# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#t'ö# #t'öö# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#variet'ee# #variet'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#variet'e# #variet'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#vernj'ee# #vernj'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#vernj'e# #vernj'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#verž'ee# #verž'e# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#verž'e# #verž'ee# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#v'öö# #v'ö# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#v'ö# #v'öö# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
#'öö# #'ö# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = 0r: stem_transform = postrule }
#'ö# #'öö# 0 0 { type = 26 && stem_transform = preexc && stem_grammar = r0: stem_transform = postrule }
