#p'äikse# #p'äikes# 0 0 { type = 10 && stem_transform = preexc && stem_grammar = bc: stem_transform = postexc }
#p'äikes# #p'äikse# 0 0 { type = 10 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#v'äikse# #v'äikes# 0 0 { type = 10 && stem_transform = preexc && stem_grammar = bc: stem_transform = postexc }
#v'äikes# #v'äikse# 0 0 { type = 10 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#'äikse# #'äikes# 0 0 { type = 10 && stem_transform = preexc && stem_grammar = bc: stem_transform = postexc }
#'äikes# #'äikse# 0 0 { type = 10 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#hiie# #hii# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#hii# #hiie# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#hirre# #hir# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#hir# #hirre# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kaane# #kaan# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kaan# #kaane# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kirre# #kir# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kir# #kirre# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kuue# #kuu# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kuu# #kuue# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kõrre# #kõr# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kõr# #kõrre# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#köie# #köi# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#köi# #köie# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#küüne# #küün# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#küün# #küüne# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#laane# #laan# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#laan# #laane# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#lapse# #las# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#las# #lapse# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#lääne# #lään# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#lään# #lääne# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#niie# #nii# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#nii# #niie# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#parre# #par# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#par# #parre# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#põie# #põi# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#põi# #põie# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#reie# #rei# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#rei# #reie# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#tõrre# #tõr# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#tõr# #tõrre# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#täie# #täi# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#täi# #täie# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#ukse# #us# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#us# #ukse# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#uue# #uu# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#uu# #uue# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#varre# #var# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#var# #varre# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#viie# #vii# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#vii# #viie# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#v'oe# #voo# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#voo# #v'oe# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#õie# #õi# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#õi# #õie# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#õrre# #õr# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#õr# #õrre# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#õõne# #õõn# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#õõn# #õõne# 0 0 { type = 14 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#esi# #'e# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#'e# #esi# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kesi# #k'e# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#k'e# #kesi# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#käsi# #k'ä# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#k'ä# #käsi# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#lüsi# #l'ü# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#l'ü# #lüsi# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#mesi# #m'e# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#m'e# #mesi# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#susi# #s'u# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#s'u# #susi# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#süsi# #s'ü# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#s'ü# #süsi# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#tõsi# #t'õ# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#t'õ# #tõsi# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#vesi# #v'e# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#v'e# #vesi# 0 0 { type = 15 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#aha# #ahe# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#ahe# #aha# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#anna# #'an# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#'an# #anna# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#haista# #haiste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#haiste# #haista# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#heida# #heide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#heide# #heida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#hoia# #h'oi# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#h'oi# #hoia# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#hüüa# #h'üü# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#h'üü# #hüüa# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#jooda# #joode# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#joode# #jooda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#jõua# #j'õu# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#j'õu# #jõua# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kanna# #k'an# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#k'an# #kanna# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#karda# #karde# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#karde# #karda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kasta# #kaste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kaste# #kasta# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#keeda# #keede# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#keede# #keeda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kesta# #keste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#keste# #kesta# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kiida# #kiide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kiide# #kiida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#koida# #koide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#koide# #koida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kosta# #koste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#koste# #kosta# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kurda# #kurde# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kurde# #kurda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#köida# #köide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#köide# #köida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#künna# #k'ün# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#k'ün# #künna# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#laida# #laide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#laide# #laida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#lase# #l'as# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#l'as# #lase# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#lausta# #lauste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#lauste# #lausta# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#leia# #l'ei# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#l'ei# #leia# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#liida# #liide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#liide# #liida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#loida# #loide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#loide# #loida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#looda# #loode# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#loode# #looda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#lõida# #lõide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#lõide# #lõida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#läida# #läide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#läide# #läida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#murra# #m'ur# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#m'ur# #murra# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#muuda# #muude# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#muude# #muuda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#mõista# #mõiste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#mõiste# #mõista# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#mõse# #m'õs# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#m'õs# #mõse# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#mõõda# #mõõde# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#mõõde# #mõõda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#naida# #naide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#naide# #naida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#n'ea# #n'ee# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#n'ee# #n'ea# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#niida# #niide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#niide# #niida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#nõua# #n'õu# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#n'õu# #nõua# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#osta# #oste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#oste# #osta# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#paista# #paiste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#paiste# #paista# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#peida# #peide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#peide# #peida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#pista# #piste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#piste# #pista# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#puse# #p'us# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#p'us# #puse# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#päästa# #pääste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#pääste# #päästa# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#püüa# #p'üü# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#p'üü# #püüa# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#reeda# #reede# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#reede# #reeda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#roida# #roide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#roide# #roida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#saada# #saade# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#saade# #saada# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#s'ea# #s'ea# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#s'ea# #s'ea# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#suuda# #suude# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#suude# #suuda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#sõida# #sõide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#sõide# #sõida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#sõua# #s'õu# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#s'õu# #sõua# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#säästa# #sääste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#sääste# #säästa# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#sööda# #sööde# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#sööde# #sööda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#söösta# #sööste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#sööste# #söösta# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#süsta# #süste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#süste# #süsta# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#taha# #tahe# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#tahe# #taha# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#t'ea# #t'ea# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#t'ea# #t'ea# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#toida# #toide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#toide# #toida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#tooda# #toode# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#toode# #tooda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#tunne# #t'un# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#t'un# #tunne# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#tõsta# #tõste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#tõste# #tõsta# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#täida# #täide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#täide# #täida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#uha# #uhe# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#uhe# #uha# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#uida# #uide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#uide# #uida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#veeda# #veede# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#veede# #veeda# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#vesta# #veste# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#veste# #vesta# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#viida# #viide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#viide# #viida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#võia# #v'õi# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#v'õi# #võia# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#võida# #võide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#võide# #võida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#väida# #väide# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#väide# #väida# 0 0 { type = 34 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#ata# #ate# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#ate# #ata# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#'atta# #'att# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#'att# #'atta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#jäta# #j'äe# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#j'äe# #jäta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#j'ätta# #j'ätt# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#j'ätt# #j'ätta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kata# #k'ae# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#k'ae# #kata# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#k'atta# #k'att# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#k'att# #k'atta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#küta# #k'öe# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#k'öe# #küta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#k'ütta# #k'ütt# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#k'ütt# #k'ütta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#lõpe# #lõpe# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#lõpe# #lõpe# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#l'õppe# #l'õpp# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#l'õpp# #l'õppe# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#mata# #m'ae# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#m'ae# #mata# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#m'atta# #m'att# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#m'att# #m'atta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#nuta# #nute# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#nute# #nuta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#n'utta# #n'utt# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#n'utt# #n'utta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#peta# #pete# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#pete# #peta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#p'etta# #p'ett# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#p'ett# #p'etta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#tapa# #tape# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#tape# #tapa# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#t'appa# #t'app# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#t'app# #t'appa# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#uta# #ute# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#ute# #uta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#'utta# #'utt# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#'utt# #'utta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#võta# #v'õe# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#v'õe# #võta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#v'õtta# #v'õtt# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#v'õtt# #v'õtta# 0 0 { type = 35 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#ahvatel# #ahvatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#ahvatell# #ahvatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#arutel# #arutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#arutell# #arutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#arvutel# #arvutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#arvutell# #arvutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#avatel# #avatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#avatell# #avatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#edvistel# #edvistell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#edvistell# #edvistel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#eritel# #eritell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#eritell# #eritel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#esitel# #esitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#esitell# #esitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#hellitel# #hellitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#hellitell# #hellitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#hirnatel# #hirnatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#hirnatell# #hirnatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#hõljuskel# #hõljuskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#hõljuskell# #hõljuskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#hüpatel# #hüpatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#hüpatell# #hüpatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#hüpitel# #hüpitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#hüpitell# #hüpitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#imestel# #imestell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#imestell# #imestel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#imetel# #imetell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#imetell# #imetel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#jalutel# #jalutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#jalutell# #jalutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kaagatel# #kaagatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kaagatell# #kaagatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kaagutel# #kaagutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kaagutell# #kaagutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kaalutel# #kaalutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kaalutell# #kaalutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#keelitel# #keelitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#keelitell# #keelitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kenitel# #kenitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kenitell# #kenitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#keskustel# #keskustell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#keskustell# #keskustel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kiljatel# #kiljatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kiljatell# #kiljatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#koputel# #koputell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#koputell# #koputel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kujutel# #kujutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kujutell# #kujutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kuulatel# #kuulatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kuulatell# #kuulatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kõigutel# #kõigutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kõigutell# #kõigutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kõnetel# #kõnetell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kõnetell# #kõnetel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#kõnniskel# #kõnniskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#kõnniskell# #kõnniskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#käsitel# #käsitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#käsitell# #käsitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#köhatel# #köhatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#köhatell# #köhatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#küsitel# #küsitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#küsitell# #küsitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#lakatel# #lakatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#lakatell# #lakatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#lamaskel# #lamaskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#lamaskell# #lamaskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#l'oetel# #l'oetell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#l'oetell# #l'oetel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#meeliskel# #meeliskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#meeliskell# #meeliskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#meelitel# #meelitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#meelitell# #meelitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#menetel# #menetell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#menetell# #menetel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#min# #minn# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#minn# #min# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#mõlgutel# #mõlgutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#mõlgutell# #mõlgutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#mõtiskel# #mõtiskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#mõtiskell# #mõtiskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#määratel# #määratell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#määratell# #määratel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#naeratel# #naeratell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#naeratell# #naeratel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#naljatel# #naljatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#naljatell# #naljatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#naudiskel# #naudiskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#naudiskell# #naudiskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#n'õutel# #n'õutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#n'õutell# #n'õutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#ol# #oll# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#oll# #ol# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#oleskel# #oleskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#oleskell# #oleskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#otsiskel# #otsiskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#otsiskell# #otsiskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#pan# #pann# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#pann# #pan# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#peesiskel# #peesiskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#peesiskell# #peesiskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#piiritel# #piiritell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#piiritell# #piiritel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#pilgutel# #pilgutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#pilgutell# #pilgutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#roomaskel# #roomaskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#roomaskell# #roomaskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#rõõmustel# #rõõmustell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#rõõmustell# #rõõmustel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#sobitel# #sobitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#sobitell# #sobitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#sosiskel# #sosiskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#sosiskell# #sosiskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#sosistel# #sosistell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#sosistell# #sosistel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#sur# #surr# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#surr# #sur# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#suunitel# #suunitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#suunitell# #suunitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#suurustel# #suurustell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#suurustell# #suurustel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#talitel# #talitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#talitell# #talitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#tantsiskel# #tantsiskell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#tantsiskell# #tantsiskel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#t'aotel# #t'aotell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#t'aotell# #t'aotel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#targutel# #targutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#targutell# #targutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#tul# #tull# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#tull# #tul# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#unistel# #unistell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#unistell# #unistel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#usutel# #usutell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#usutell# #usutel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#vallatel# #vallatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#vallatell# #vallatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#viimistel# #viimistella# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#viimistella# #viimistel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#viivitel# #viivitell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#viivitell# #viivitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#võpatel# #võpatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#võpatell# #võpatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#välgatel# #välgatell# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#välgatell# #välgatel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#õnnitel# #õnnitella# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#õnnitella# #õnnitel# 0 0 { type = 36 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#j'uu# #j'õ# 0 0 { type = 38 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#j'õ# #j'uu# 0 0 { type = 38 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#l'uu# #l'õ# 0 0 { type = 38 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#l'õ# #l'uu# 0 0 { type = 38 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#l'üü# #l'õ# 0 0 { type = 38 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#l'õ# #l'üü# 0 0 { type = 38 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#s'üü# #s'õ# 0 0 { type = 38 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#s'õ# #s'üü# 0 0 { type = 38 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
#t'uu# #t'õ# 0 0 { type = 38 && stem_transform = preexc && stem_grammar = bc: stem_transform = postrule }
#t'õ# #t'uu# 0 0 { type = 38 && stem_transform = preexc && stem_grammar = cb: stem_transform = postrule }
