Q1Q1 Q1 !WW W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
ss s !WWL W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
ss s WW W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
p b WW W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
p b WL W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
p b !WW JW { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
k g WW W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
k g WL W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
k g !WW JW { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
t d WW W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
t d WL W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
t d !WW JW { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
b m !WWm E { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
d n !WWn E { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
d l !WWl E { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
d r !WWr E { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
t 0 !WWh W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
k 0 !WWh W { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
k 0 Ws E { stem_transform = prerule && stem_grammar = tn: stem_transform = postrule }
0 0 0 0 { stem_grammar = tn && stem_transform = prerule: stem_transform = postrule }
