0 s ja # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
0 s Aka # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
0 s Nga # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
da 0 !WWZe # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 kond # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 k'ond # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 likum # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
i 0 Cikum # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
i 0 Aikum # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 Dum # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
i 0 WWGam # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
i 0 Skam # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 Tam # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 likem # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 Tem # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 Wiem # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 Wuem # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 Tim # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 Eim # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
va ev WWt # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
va ev WWd # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
va ev Wst # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
va ev WRd # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 Wiav # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 Wiuv # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 CAv # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 WZin # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 WCits # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
a 0 WZZits # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el WWG # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el Wmb # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el WRd # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el WRg # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el WWK # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el !WWK # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el Wmp # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el WRk # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el WRt # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el WSK # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el WWs # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el WKs # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el Wmps # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el Wnts # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el WWv # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
li el Whv # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er WWG # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er Wmb # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er WNd # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er WNg # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er Wmp # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er WWK # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er !WWK # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er Wpt # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er WNk # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er WNt # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er WSK # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er WWs # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er WWv # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
ri er Whv # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
i 0 C # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
se (ne) Wke # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
se ne C # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
se ne a # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
se ne e # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
se ne li # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
se ne mi # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
se ne stiku # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
e 0 ius # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
e 0 eus # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
e 0 ias # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
e 0 ies # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
e 0 CWs # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
u 0 Ing # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
u 0 !Wikk # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
u 0 !WIk # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
0 e !WWZel # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
el le !WWK # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
el le WWC # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
el le WCC # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
el le WCCC # { stem_transform = prerule && stem_grammar = ba: stem_transform = postrule }
