d d oi i { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
g g oo i { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
g g faa i { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
Q1 Q1Q1 !WW W { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
s ss !WWL W { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
g k WW W { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
g k WL W { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
g k !WW JW { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
d t WW W { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
d t WL W { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
d t !WW JW { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
b p WW W { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
b p WL W { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
b p !WW JW { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
N1 d !WWN1 E { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
m b !WWm E { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
0 t !WWh E { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
0 k !WWs E { stem_transform = prerule && stem_grammar = nt: stem_transform = postrule }
0 0 0 0 { stem_grammar = nt && stem_transform = prerule: stem_transform = postrule }
