0 se Wke # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
ne se C # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
ne se A # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
le el WWC # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
le el !WWK # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
le el WCC # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
le el WCCC # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li WWG # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li Wmb # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li WRd # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li WRg # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li WWK # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li !WWK1K1 # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li Wmp # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li WRk # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li WRt # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li WSK # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li WWs # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li WKs # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li Wmps # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li Wnts # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li WWv # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
el li Whv # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er eri WrC # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er eri EiG # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri WWG # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri Wmb # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri WNd # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri WNg # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri Wmp # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er eri p # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri WWK # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri !WWK1K1 # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri Wpt # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri WNk # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri WNt # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri WSK # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri WWs # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri WWv # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
er ri Whv # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
e 0 !WWZel # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 da !WWZe # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a kond # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a k'ond # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 u Ing # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 u !WIk # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a likum # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 i Cikum # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 i Aikum # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a Dum # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 i WWGam # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 i Skam # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a Tam # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a likem # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a Tem # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a Wiem # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a Wuem # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a Tim # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a Eim # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a WZin # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a WCits # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a WZZits # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
ev va WWt # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
ev va WWd # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
ev va Wst # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
ev va WRd # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a Wiav # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a Wiuv # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 a CAv # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
s 0 ja # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
s 0 Aka # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
s 0 Nga # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 e ius # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 e eus # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 e ias # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 e ies # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 e CWs # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
0 i C # { stem_transform = prerule && stem_grammar = ab: stem_transform = postrule }
